/** A touch-first canvas expedition for phones whose browser cannot expose WebGPU. */
export function startPocketExpedition(canvas, audio) {
    const ctx = canvas.getContext("2d");
    const state = { x: .47, y: .66, yaw: 0, moveX: 0, moveY: 0, surf: false, spell: 0, spellT: 0, flakes: [], last: performance.now() };
    for (let i = 0; i < 100; i++) state.flakes.push({ x: Math.random(), y: Math.random(), z: .2 + Math.random() });
    const hud = document.createElement("div");
    hud.id = "pocket-hud";
    hud.innerHTML = `<div class="pocket-title">HIMLANDS <span>POCKET EXPEDITION</span></div><button class="pocket-dir" aria-label="Directions">N</button><button class="pocket-stick" aria-label="Move"><i></i></button><div class="pocket-look" aria-label="Look"></div><button class="pocket-surf" aria-label="Hold to surf">❄</button><div class="pocket-spells">${[1,2,3,4,5].map(n=>`<button data-spell="${n}">${n}</button>`).join("")}</div>`;
    document.body.append(hud);
    const style = document.createElement("style"); style.textContent = `#pocket-hud{position:fixed;inset:0;z-index:61;color:#eaf7ff;font:600 10px/1 ui-sans-serif,system-ui;pointer-events:none}#pocket-hud button{pointer-events:auto;color:#eaf7ff;border:1px solid #b9e4ff99;background:#07111d30;backdrop-filter:blur(5px);box-shadow:inset 0 0 22px #9ee8ff14,0 2px 16px #0004;touch-action:none}.pocket-title{position:absolute;top:max(18px,env(safe-area-inset-top));left:50%;transform:translateX(-50%);letter-spacing:.34em;text-align:center;text-shadow:0 2px 10px #000}.pocket-title span{display:block;margin-top:7px;font-size:7px;letter-spacing:.24em;opacity:.65}.pocket-dir{position:absolute;top:18px;right:18px;width:38px;height:38px;border-radius:50%}.pocket-stick{position:absolute;bottom:24px;left:20px;width:124px;height:124px;border-radius:50%}.pocket-stick i{position:absolute;left:40px;top:40px;width:40px;height:40px;border:1px solid #eaf7ff;border-radius:50%}.pocket-look{position:absolute;right:0;bottom:0;width:48vw;height:60vh;pointer-events:auto}.pocket-surf{position:absolute;bottom:26px;left:50%;transform:translateX(-50%);width:58px;height:58px;border-radius:50%;font-size:18px}.pocket-spells{position:absolute;right:18px;bottom:120px;display:grid;gap:9px}.pocket-spells button{width:44px;height:44px;border-radius:50%}.pocket-spells button:active,.pocket-surf:active{background:#89d8ff55}@media(pointer:fine){#pocket-hud{display:none}}`; document.head.append(style);
    const stick = hud.querySelector(".pocket-stick"), knob=stick.querySelector("i");
    const move = e => { const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy)||1,m=Math.min(1,l/(r.width*.32));state.moveX=dx/l*m;state.moveY=dy/l*m;knob.style.transform=`translate(${dx/l*m*28}px,${dy/l*m*28}px)`; };
    stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);move(e)}; stick.onpointermove=e=>{if(e.buttons)move(e)}; ["pointerup","pointercancel"].forEach(k=>stick.addEventListener(k,()=>{state.moveX=state.moveY=0;knob.style.transform=""}));
    let lx=0; const look=hud.querySelector(".pocket-look"); look.onpointerdown=e=>{lx=e.clientX;look.setPointerCapture(e.pointerId)}; look.onpointermove=e=>{if(e.buttons){state.yaw+=(e.clientX-lx)*.006;lx=e.clientX}};
    const surf=hud.querySelector(".pocket-surf"); surf.onpointerdown=e=>{e.preventDefault();surf.setPointerCapture(e.pointerId);state.surf=true;audio.unlock()}; ["pointerup","pointercancel"].forEach(k=>surf.addEventListener(k,()=>state.surf=false));
    hud.querySelectorAll("[data-spell]").forEach(b=>b.onpointerdown=e=>{e.preventDefault();audio.unlock();state.spell=+b.dataset.spell;state.spellT=1.2;audio.spell(state.spell)});
    function frame(now) { const dt=Math.min(.05,(now-state.last)/1000); state.last=now; state.x=Math.max(.13,Math.min(.87,state.x+state.moveX*dt*(state.surf?.22:.11)));state.y=Math.max(.44,Math.min(.82,state.y+state.moveY*dt*(state.surf?.18:.09)));state.spellT=Math.max(0,state.spellT-dt); const w=canvas.width=innerWidth*devicePixelRatio,h=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const W=innerWidth,H=innerHeight;const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#0b2034");g.addColorStop(.48,"#d6bd91");g.addColorStop(.49,"#9cb6c6");g.addColorStop(1,"#0a1725");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#e6f5ff";for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(-W*.1+i*W*.18,H*.56);ctx.lineTo((i+.5)*W*.18,H*(.25+((i%3)*.06)));ctx.lineTo((i+1)*W*.18,H*.56);ctx.fill()}ctx.fillStyle="#bcd6e4";ctx.beginPath();ctx.moveTo(0,H*.54);ctx.quadraticCurveTo(W*.45,H*.47,W,H*.58);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();if(state.surf){ctx.strokeStyle="#dff8ff88";ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(state.x*W,state.y*H,55,12,0,0,7);ctx.stroke()}if(state.spellT){const r=(1.2-state.spellT)*110+22;ctx.strokeStyle=["#82dcff","#8bc9ff","#d9f6ff","#b8eeff","#b3dcff"][state.spell-1];ctx.lineWidth=3;ctx.beginPath();ctx.arc(state.x*W,state.y*H,r,0,7);ctx.stroke()}ctx.fillStyle="#142333";ctx.fillRect(state.x*W-13,state.y*H-50,26,48);ctx.fillStyle="#d9b27e";ctx.beginPath();ctx.arc(state.x*W,state.y*H-60,12,0,7);ctx.fill();ctx.fillStyle="#fff";for(const f of state.flakes){f.y+=dt*.05*f.z;if(f.y>1)f.y=0;ctx.globalAlpha=f.z*.7;ctx.fillRect(f.x*W,f.y*H,2,2)}ctx.globalAlpha=1;requestAnimationFrame(frame)}requestAnimationFrame(frame);
}
